#pragma once

// Generated by scripts/generate_led_strip_images.py. Do not edit manually.

#include "config.h"

#include <stdint.h>

enum class LEDStripAnimation : uint8_t {
    Off = 0,
    Bootup = 1,
    Idle = 2,
    Forward = 3,
    Failsafe = 4,
    LowBattery = 5,
    HardwareError = 6,
    TestPattern = 7,
    Image = 8
};

namespace LEDStripImages {
constexpr uint16_t GENERATED_LED_COUNT = 14;
constexpr uint16_t GENERATED_SECTOR_COUNT = 42;

static_assert(RobotConfig::LED_STRIP_LED_COUNT == GENERATED_LED_COUNT,
              "Regenerate the LED-strip images after changing LED_STRIP_LED_COUNT");
static_assert(RobotConfig::LED_STRIP_SECTOR_COUNT == GENERATED_SECTOR_COUNT,
              "Regenerate the LED-strip images after changing the strip sector count");

bool hasImage(LEDStripAnimation animation);
const uint32_t* getSectorPixels(LEDStripAnimation animation, uint16_t sector);
} // namespace LEDStripImages
